@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjllYWEwMjZmNjM1MTU3ZGZhZDUzMmU0MTgzYTZiODIzZDc1MmFkMWQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiMzE0OTAwMzYyMjExLTdqOGhhYm5ndGhjNWVyMmJ2MDVqM2wyZTJlaWZnbTNoLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMzE0OTAwMzYyMjExLTdqOGhhYm5ndGhjNWVyMmJ2MDVqM2wyZTJlaWZnbTNoLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAzMDE2NTUwNzUwMDQ3NjI1MTg3IiwiZW1haWwiOiJmb203OGhAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiIzZllob213MTNjcVpIazZNUXpiNGdRIiwiaWF0IjoxNjQzMzI4ODc0LCJleHAiOjE2NDMzMzI0NzR9.eSDamFdxMRchqSQf36NIKFa5TQqN0Rdwou_N80FUJlrjE5Lrxr-IoR4xQ6FWIx-3Yly-Jwo53qMAARJWnOJ70TaFxLmVuqs80gmooc-3ftmxcady7NDpzMfeQvPrdKU9Sg162WXYidc8r4bsgOmwLpRlL1LWlu9DOUf0S1z90w4XkDEHQNcBpTdicDYBdXyLabosXZURAzInr3u5yYMa2u4QbSdXTsnnJkl_Zlyt6S87eLaHwN2fZ22e42ghoQc-ptb-ZH2eCqUJhuoHf9QP3RaIR8xLIbRF__C-HeDWeRxdGCRFo9o_fh8DbQVnKigNiD4GpHp8gMYUCaROch-d2Q
@tokenFalsoTest = yygsahygsaudfkjsahf
###
GET http://localhost:4000/api/v1/operations
x-access-token:{{tokenFalsoTest}}
Content-Type: application/json 

###
POST http://localhost:4000/api/v1/operations
x-access-token:{{tokenFalsoTest}}
Content-Type: application/json 

{
    "concept":"Mouse!!!Q",
    "type": "expenditure",
    "categoryId": 5,
    "amount": 5556,
    "date": "2021-03-25"
}


###
DELETE http://localhost:4000/api/v1/operations/19
Content-Type: application/json 

{
    "actualUserId":1
}
###
PUT http://localhost:4000/api/v1/operations/23
Content-Type: application/json 

{
    "concept":"Algo Editado",
    "amount": 51,
    "categoryId": 5,
    "date": "2021-12-17"
}

###
GET http://localhost:4000/api/v1/operations/40
x-access-token:{{token}}
Content-Type: application/json 


###
GET http://localhost:4000/api/v1/categories
x-access-token:{{token}}
Content-Type: application/json 

###
POST http://localhost:4000/api/v1/auth
x-access-token:{{tokenFalsoTest}}
Content-Type: application/json 

{
    "user":{"uid":"eererer43545"}
}