@token = eyJhbGciOiJSUzI1NiIsImtpZCI6IjllYWEwMjZmNjM1MTU3ZGZhZDUzMmU0MTgzYTZiODIzZDc1MmFkMWQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJhY2NvdW50cy5nb29nbGUuY29tIiwiYXpwIjoiMzE0OTAwMzYyMjExLTdqOGhhYm5ndGhjNWVyMmJ2MDVqM2wyZTJlaWZnbTNoLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwiYXVkIjoiMzE0OTAwMzYyMjExLTdqOGhhYm5ndGhjNWVyMmJ2MDVqM2wyZTJlaWZnbTNoLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tIiwic3ViIjoiMTAxODc1MDAyNDA1OTE4OTEwNDM5IiwiZW1haWwiOiJmb203OGFAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJzYWlqVEdIQmlCZmhNeDZCUmtQdXlRIiwiaWF0IjoxNjQzMzA3NDAzLCJleHAiOjE2NDMzMTEwMDN9.LToUR4zwSJDhHNu7YXjQ4povz-BLtunVGDvmc50VdOPZTHAO4WyVXle4EqMDDOYUQhvAj7wEeXrXm6NKfRP2QfnFldXY2H0bOnxrd6YYzyN1S4r7Evp6PpqlonxNSQxcZkUSBRxQ8ots6T0FgjDsozOdM3-UYB7ta8Xc5TDS24bg2e8oLTUrXBv3p8TVrBH2BevpOXZQYI4m_o7tKn58iewJ22mcZDQLXj6AKnKzhGw2Ejn99JVcueZfBudOtQJrpXX02kfdo9HDhmCO_QMKTiKb5nQPQo9V0e6FAftfd-BbVCz_c7SsU4_RVz78Z3lTW7A_2A-jSXRrulCuNd2mvg

###
GET http://localhost:4000/operations
x-access-token:{{token}}
###
POST http://localhost:4000/operations
Content-Type: application/json 

{
    "concept":"Mouse",
    "type": "expenditure",
    "categoryId": 74,
    "amount": 343,
    "date": "2021-03-25"
}

###
POST http://localhost:4000/operations
Content-Type: application/json 

{
    "concept":"Salary",
    "type": "income",
    "categoryId": 6,
    "amount": 2100,
    "date": "2021-11-02"
}

###
DELETE http://localhost:4000/operations/7

###
PUT http://localhost:4000/operations/30
Content-Type: application/json 

{
    "concept":"Algoul",
    "amount": 51,
    "categoryId": 5,
    "date": "2021-12-17"
}

###
GET http://localhost:4000/operations/30