###
GET http://localhost:4000/operations

###
POST http://localhost:4000/operations
Content-Type: application/json 

{
    "concept":"Mouse",
    "type": "expenditure",
    "categoryId": 74,
    "amount": 343,
    "date": "2021-03-25"
}

###
POST http://localhost:4000/operations
Content-Type: application/json 

{
    "concept":"Salary",
    "type": "income",
    "categoryId": 6,
    "amount": 2100,
    "date": "2021-11-02"
}

###
DELETE http://localhost:4000/operations/7

###
PUT http://localhost:4000/operations/5
Content-Type: application/json 

{
    "concept":"PR in web of Paul",
    "amount": 550,
    "categoryId": 8,
    "date": "2021-12-17"
}

###
GET http://localhost:4000/operations/5